# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63724baa0595d3fcb2e6f533063cdbc1cba92fd97954c1a4398bcf94a994829a4babe2de130c4e5f2300b5e9c3cde821b956077dff96504fac04b77af7c375fb

test:
  secret_key_base: 8597080bb15946fc908628d427b307786d948d050cce441ce2e11ef3605941aef1712334f0d14874cbea6adfa30968b4a50fec970d3b7720eedd00ac703d9975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
